name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      - legacy
      - min
      - medium
      - branch-v2.973
      - branch-v2.975
      - branch_v2.982
      - dev-level
      - develop
  pull_request:
    branches:
      - master
      - dev
      - legacy
      - min
      - medium
      - branch-v2.973
      - branch-v2.975
      - branch_v2.982
      - dev-level
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: "adopt"
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Run Tests
      run: ./gradlew testOssDebugUnitTest
    - name: Build with Gradle
      run: ./gradlew assembleSnapshot
    - name: Upload Artifacts - OSS version
      uses: actions/upload-artifact@v2
      with:
        name: SkyTube-Oss.apk
        path: app/build/outputs/apk/oss/snapshot/SkyTube-Oss-*.apk
    - name: Upload Artifacts - Extra version
      uses: actions/upload-artifact@v2
      with:
        name: SkyTube-Extra.apk
        path: app/build/outputs/apk/extra/snapshot/SkyTube-Extra-*.apk
